import type { DecisionPlan } from "../../types";

/**
 * 3b-4: Trip brief generation.
 *
 * Builds a clean, mobile-readable markdown document from a DecisionPlan.
 * Covers all scenario types: date_night, weekend_trip, city_trip, big_purchase.
 * Pure function — no external calls, no side effects.
 */
export function buildPlanBrief(plan: DecisionPlan): string {
  const lines: string[] = [];

  // ── Title line ──────────────────────────────────────────────────────────────
  const dateStr = plan.event_datetime
    ? ` — ${formatBriefDate(plan.event_datetime)}`
    : "";
  lines.push(`# ${plan.title}${dateStr}`);
  lines.push("");
  lines.push(plan.summary);
  lines.push("");

  // ── Primary plan ────────────────────────────────────────────────────────────
  const p = plan.primary_plan;

  lines.push(`## Primary: ${p.title}`);
  lines.push("");

  if (p.estimated_total) {
    lines.push(`**Estimated total:** ${p.estimated_total}`);
  }

  if (plan.event_location) {
    lines.push(`**Location:** ${plan.event_location}`);
  }

  if (plan.event_datetime) {
    lines.push(`**When:** ${formatBriefDatetime(plan.event_datetime)}`);
  }

  if (p.timing_note) {
    lines.push(`**Timing:** ${p.timing_note}`);
  }

  lines.push("");

  if (p.why_this_now) {
    lines.push(`**Why this:** ${p.why_this_now}`);
    lines.push("");
  }

  // Highlights (bullet list of key details)
  if (p.highlights.length > 0) {
    lines.push("### Details");
    p.highlights.forEach((h) => lines.push(`- ${h}`));
    lines.push("");
  }

  // Tradeoffs
  if (p.tradeoffs.length > 0) {
    lines.push("### Tradeoffs");
    p.tradeoffs.forEach((t) => lines.push(`- ${t}`));
    lines.push("");
  }

  // ── Credit card callout ──────────────────────────────────────────────────────
  if (plan.trip_card_callout) {
    lines.push(`💳 ${plan.trip_card_callout}`);
    lines.push("");
  }

  // ── Comparative summary ──────────────────────────────────────────────────────
  if (plan.tradeoff_summary) {
    lines.push("### Comparison");
    lines.push(plan.tradeoff_summary);
    lines.push("");
  }

  // ── Risks ────────────────────────────────────────────────────────────────────
  if (plan.risks.length > 0) {
    lines.push("## Key risks");
    plan.risks.forEach((r) => lines.push(`- ${r}`));
    lines.push("");
  }

  // ── Backup options ───────────────────────────────────────────────────────────
  if (plan.backup_plans.length > 0) {
    lines.push("## Backup options");
    plan.backup_plans.forEach((b) => {
      const reason = b.tradeoff_reason ?? b.tradeoff_detail ?? b.summary ?? "";
      lines.push(`### ${b.label}: ${b.title}`);
      if (b.estimated_total) lines.push(`**Estimated total:** ${b.estimated_total}`);
      if (reason) lines.push(reason);
      lines.push("");
    });
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push(`*Generated by Onegent · Plan ID: ${plan.id}*`);

  return lines.join("\n");
}

/** Format "2026-04-12T19:30:00" → "Apr 12, 2026" */
function formatBriefDate(iso: string): string {
  const parts = iso.split("T")[0].split("-");
  if (parts.length !== 3) return iso;
  const [year, month, day] = parts.map(Number);
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${months[month - 1]} ${day}, ${year}`;
}

/** Format "2026-04-12T19:30:00" → "Apr 12, 2026 at 7:30 PM" */
function formatBriefDatetime(iso: string): string {
  const [datePart, timePart] = iso.split("T");
  const dateStr = formatBriefDate(iso);
  if (!timePart) return dateStr;
  const [hh, mm] = timePart.split(":").map(Number);
  const period = hh >= 12 ? "PM" : "AM";
  const hour = hh % 12 || 12;
  const min = String(mm).padStart(2, "0");
  return `${dateStr} at ${hour}:${min} ${period}`;
}
